-- liquibase formatted sql

-- changeset Kaer:1
CREATE TABLE category (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   category_name VARCHAR UNIQUE NOT NULL
);
CREATE TABLE news (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   content TEXT NOT NULL,
   publish_date date NOT NULL,
   category_id BIGINT NOT NULL REFERENCES category(id) ON DELETE CASCADE
);