version: '3.1'

networks:
  news-net:

volumes:
  news-db:

services:

  news-postgresql:
    container_name: news-postgresql
    image: news-postgresql
    build:
      context: ./docker-images/postgresql/
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    networks:
      news-net:
    ports:
      - "50001:5432"
    volumes:
      - news-db:/var/lib/postgresql/data
      - .\init-db.sql:/docker-entrypoint-initdb.d/init-db.sql


